<?php
/**
 * Copyright © Ronan Guérin. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
    require(['jquery','barbajs'], function($, barba) {
        barba.init({
            timeout: 10000,
            transitions: [{
                name: 'default-transition',
                leave() {
                    console.log("Leave...")
                    $("html, body").scrollTop(0)
                },
                enter(data) {
                    console.log("Enter...")
                    $(data.next.container).trigger('contentUpdated');
                }
            }]
        });
    })
</script>
