<?php
/**
 * Copyright © Ronangr1. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
    require(['Ronangr1_Barbagento/js/barba-init'], function (MagentoBarba) {
        const config = {
            timeout: 7000,
            debug: false,
            excludedPages: ['/checkout', '/cart', '/customer/account'],
        }

        console.log(config)

        MagentoBarba.init(config);
    })
</script>
